@api_url = http://localhost:{{$dotenv PORT}}

### invalid request
GET {{api_url}}
Authorization: Bearer {{$dotenv SESSION_SECRET}}

### valid request
POST {{api_url}}/sanitize
Authorization: Bearer {{$dotenv SESSION_SECRET}}
x-unique-id: 1234567890
x-lang: es
Content-Type: application/json

{
  "data": "<script>alert('XSS')</script>",
  "comment": "   Hola Mundo!   ",
  "test": "Hello\\x00\nWorld\\x1F!"
}


### jwt request
POST {{api_url}}/auth/generate-token
Authorization: Bearer {{$dotenv SESSION_SECRET}}
x-unique-id: junforever
x-lang: es
Content-Type: application/json

{
  "role": "admin"
}

###

@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVJZCI6Imp1bmZvcmV2ZXIiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDYwNDU1NjcsImlhdCI6MTc0NjA0NDY2N30.0rbg2KT_McpPAecQ4bgGGAmj81dCJ-1XgSITxNDSftw"

### jwt validation
POST {{api_url}}/auth/verify-token
Authorization: Bearer {{$dotenv SESSION_SECRET}}
x-unique-id: junforever
x-lang: es
Content-Type: application/json

{
  "token": {{token}}
}


### logout
POST {{api_url}}/auth/logout
Authorization: Bearer {{$dotenv SESSION_SECRET}}
x-unique-id: junforever
x-lang: es
Content-Type: application/json

{
  "token": {{token}}
}

