@api_url = http://localhost:{{$dotenv PORT}}
@clientId = 445565377
@uniqueId = 445565377

### invalid request
GET {{api_url}}/test
x-unique-id: {{uniqueId}}

### valid request
POST {{api_url}}/sanitize
Authorization: Bearer {{$dotenv SESSION_SECRET}}
accept-language: es
x-unique-id: {{uniqueId}}
x-client-id: {{clientId}}

Content-Type: application/json

{
  "data": "<script>alert('XSS')</script>",
  "comment": "   Hola Mundo!   ",
  "test": "Hello\\x00\nWorld\\x1F!"
}


### jwt request
POST {{api_url}}/auth/generate-token
Authorization: Bearer {{$dotenv SESSION_SECRET}}
accept-language: es
x-unique-id: {{uniqueId}}
x-client-id: {{clientId}}

Content-Type: application/json

{
  "role": "admin"
}

###

@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVJZCI6Imp1bmZvcmV2ZXIiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDYwNDU1NjcsImlhdCI6MTc0NjA0NDY2N30.0rbg2KT_McpPAecQ4bgGGAmj81dCJ-1XgSITxNDSftw"

### jwt validation
POST {{api_url}}/auth/verify-token
Authorization: Bearer {{$dotenv SESSION_SECRET}}
accept-language: es
x-unique-id: {{uniqueId}}
x-client-id: {{clientId}}

Content-Type: application/json

{
  "token": {{token}}
}


### logout
POST {{api_url}}/auth/logout
Authorization: Bearer {{$dotenv SESSION_SECRET}}
accept-language: es
x-unique-id: {{uniqueId}}
x-client-id: {{clientId}}
Content-Type: application/json

{
  "token": {{token}}
}

